import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/layouts/header";
import SocialBar from "@/Components/ui/SocialBar";
import SplashCursor from "@/Components/ui/SplashCursor";
import Footer from "@/Components/layouts/footer";
import ShootingStarsBackground from "@/Components/ui/ShootingStarEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PortFolio | Tushar Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        {/* BACKGROUND LAYER (ALWAYS FIRST) */}
        <ShootingStarsBackground />

        {/* APP LAYER */}
        <div id="app-root">
          <Header />
          <SplashCursor />
          <SocialBar />

          <main>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
